config/routes.rb
Rails.application.routes.draw do


#devise関連
devise_for :users, :controllers => {
  :registrations => 'devise/users/registrations',
  :sessions => 'devise/users/sessions',
  :passwords => 'devise/users/passwords'
}

devise_scope :user do
  get "user/:id", :to => "users/registrations#detail"
  get "signup", :to => "users/registrations#new"
  get "login", :to => "users/sessions#new"
  get "logout", :to => "users/sessions#destroy"
  get "password", :to => "users/passwords#new"
end

#Adminのdevise
devise_for :admins, :controllers => {
  :registrations => 'devise/admins/registrations',
  :sessions => 'devise/admins/sessions',
  :passwords => 'devise/admins/passwords'
}



#Top画面
root to: 'public/homes#top'
get '/about' => 'public/homes#about'

#scope module: :public doでpublicフォルダへまとめる。※URLにpublicがつくことはない
scope module: :public do

  get 'search/search'
  get 'search/genre_search'
  get 'sort' => 'items#sort'
  get 'genre_sort' => 'search#genre_sort'
  get 'search_sort' => 'search#search_sort'

  get 'items/condition_search' => 'items#condition_search'
  resources :items, only: [:index, :show] do
    resources :reviews
  end

  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :create, :destroy, :destroy_all, :update] do
    collection do
      post :shipping_confirm
    end
  end


  get 'orders/thanks' => 'orders#thanks'
  resources :orders, only: [:show, :index, :new, :create] do
    collection do
      post :confirm
      post :pay
    end
  end

  patch 'users/:id/update_password' => 'users#update_password', as: 'update_password'
  get 'users/:id/newpassword' => 'users#newpassword'
  get 'users/unsubscribe' => 'users#unsubscribe'
  patch 'users/withdraw' => 'users#withdraw'
  resources :users, only: [:update, :show, :edit]

  resources :deliveries, only: [:update, :index, :create, :destroy, :edit]

end

#お問い合わせのルーティング
post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
post 'contacts/back', to: 'contacts#back', as: 'back'
get 'done', to: 'contacts#done', as: 'done'
resources :contacts, only: [:new, :create]

#devise以外のadminを下にまとめる

namespace :admin do
  resources :items, only: [:index, :create, :new, :update, :destroy, :show, :edit]
end

namespace :admin do
  resources :genres, only: [:index, :create, :new, :update, :destroy, :show, :edit]
end

namespace :admin do
  resources :users, only: [:index, :edit, :update, :show]
end

namespace :admin do
  resources :orders, only: [:index, :show, :update]
end

namespace :admin do
  resources :order_details, only: [:update]
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  
  validates :image, presence: true
  validates :item_name, length: {minimum: 1, maximum:60}, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, numericality: true, presence: true
  
  has_many :reviews
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  attachment :image
  
  enum is_active:{販売中:true, 販売停止中:false}
  
  def self.sort(selection)
    case selection
      when 'new'
        return all.order(created_at: :DESC)
      when 'high'
        return all.order(price: :DESC)
      when 'low'
        return all.order(price: :ASC)
    end  
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    #@items = Item.all.order(created_at: :desc)
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(8)
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "製品の登録をしました。"
    redirect_to admin_items_path
    else
      render :new
    end
  end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    if @item.save
      flash[:notice] = "製品の編集を保存しました。"
      redirect_to admin_items_path
    else
      render :new
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    flash[:notice] = "製品を削除しました。"
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :item_name, :image, :introduction, :price, :is_active)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def index
    @items = Item.all.order(created_at: :desc)
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
  end
  
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">

    <div class="mx-auto">
      <h3 class="mt-3 mb-3 col-4">製品編集</h3>
      <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch , local: true do |f| %>
      
        <% if @item.errors.any? %>
        <div class="error-explanation">
          <h3><%= @item.errors.count %>件のエラーが発生しております。</h3>
          <% @item.errors.full_messages.each do |message| %>
            <ul>
              <li>・<%= message %></li>
            </ul>
          <% end %>
        </div>
        <% end %>
        <table class="table table-sm table-borderless">
          <tr>
            <td scope="col">商品画像</td>
            <td scope="col"><%= f.attachment_field :image %></td>
          </tr>
          <tr>
            <td>商品名</td>
            <td><%= f.text_field :item_name, class: "item-edit-txt" %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= f.text_area :introduction, class: "item-edit-explination" %></td>
          </tr>
          <tr>
            <td>ジャンル</td>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :genre_name, include_blank: "--選択してください--" %></td>
          </tr>
           <tr>
            <td>税抜価格</td>
            <td><%= f.text_field :price, class: "item-edit-txt" %></td>
          </tr>
           <tr>
            <td>販売ステータス</td>
            <td><%= f.radio_button :is_active, "販売中" %>
                <%= f.label :is_active, "販売中"%>
                <%= f.radio_button :is_active, "販売停止中" %>
                <%= f.label :is_active, "販売停止中" %>
            </td>
          </tr>
        </table>
        <div class="text-center mb-5">
            <%= f.submit "編集を保存", class: "btn btn-success mt-2" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container-fluid">
  
  <h2 class="mt-4 mb-3 text-center">商品一覧</h2>
  <div class="row">
    <div class="col-lg-12 col-md-8 sc-table my-3">
      <%= search_form_for(@q, url: admin_items_path) do |f| %>
        <%= f.label :id, "商品ID" %>
        <%= f.search_field :id_eq %>
        <%= f.label :item_name, "商品名" %>
        <%= f.search_field :item_name_cont %>
        <%= f.label :item_name, "価格　" %>
        <%= f.search_field :price_gteq, placeholder:"$ Min"  %>〜<%= f.search_field :price_lteq, placeholder:"$ Max" %>
        <%= f.label :item_name, "ジャンル" %>
        <%= f.select :genre_id_eq, options_from_collection_for_select(Genre.all, :id, :genre_name), include_blank: "--選択してください--" %>
        <%= f.submit "検索", class:"btn-info px-3" %>
      <% end %>
    </div>
  </div>

  <div class="sc-table">
    <table class="table table-hover px-2">
      <thead  class="active">
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>価格</th>
            <th>ジャンル</th>
            <th>販売ステータス</th>
            <th>
            <%= link_to new_admin_item_path, class:"btn btn-success btn-sm text-center", style:"margin-bottom: -4px;" do %>
              <i class="fas fa-plus-circle"></i>製品を新規追加
            <% end %></th>
          </tr>
      </thead>
      <tbody style="background-color: #F4F8F3;">
        <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td>
              <%= link_to admin_item_path(item.id) do %>
                <%= item.item_name %>
              <% end %>
            </td>
            <td>$ <%= number_with_precision(item.price.to_s(:delimited), precision: 2) %></td>
            <td><%= item.genre.genre_name %></td>
            <td>
              <% if item.is_active == "販売中" %>
                <span style="color:#49C918;"><%= item.is_active %></sapn>
              <% else %>
                <span style="color:#C0C2BF;"><%= item.is_active %></sapn>
              <% end %>
            </td>
            <td><%= link_to "削除", admin_item_path(item.id), method: :delete, data:{confirm:"本当に削除しますか？"}, class:"text-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>	
  <%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">

    <div class="mx-auto">
      <h3 class="mt-3 mb-3 col-4">製品登録</h3>

      <%= form_with model: @item, url: admin_items_path, method: :post,local: true do |f| %>
      
        <% if @item.errors.any? %>
          <div class="error-explanation">
            <h3><%= @item.errors.count %>件のエラーが発生しております。</h3>
            <% @item.errors.full_messages.each do |message| %>
              <ul>
                <li>・<%= message %></li>
              </ul>
            <% end %>
          </div>
        <% end %>
        
        <table class="table table-sm table-borderless">
          <tr>
            <td scope="col">商品画像</td>
            <td scope="col"><%= f.attachment_field :image %></td>
          </tr>
          <tr>
            <td>商品名</td>
            <td><%= f.text_field :item_name, class: "item-edit-txt" %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= f.text_area :introduction, class: "item-edit-explination" %></td>
          </tr>
          <tr>
            <td>ジャンル</td>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :genre_name, include_blank: "--選択してください--" %></td>
          </tr>
           <tr>
            <td>税抜価格</td>
            <td><%= f.text_field :price, class: "item-edit-txt" %></td>
          </tr>
           <tr>
            <td>販売ステータス</td>
            <td><%= f.radio_button :is_active, "販売中" %>
                <%= f.label :is_active, "販売中"%>
                <%= f.radio_button :is_active, "販売停止中" %>
                <%= f.label :is_active, "販売停止中" %>
            </td>
          </tr>
        </table>
        <div class="text-center mb-5">
          <%= f.submit "製品を追加", class: "btn btn-success mt-2" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
	<h3 class="mt-4 mb-5">製品詳細</h3>
  <div class="row">
    <div class="col-xs-3 mx-auto mb-2">
      <%= attachment_image_tag @item, :image, size: "350x350", fallback: "no-image.jpeg", format: "jpeg", class: "card", style: "border: 2px solid grey;" %>
    </div>
    <div class="col-xs-5 col-md-6">
      <table class="table table-sm table-borderless mx-auto" style="border-collapse: separate; border-spacing: 5px;">
        <tr>
          <td scope="col"><h3>商品名</h3></td>
          <td scope="col"><h3><%= @item.item_name %></h3></td>
        </tr>
        <tr>
          <td>紹介説明</td>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= @item.genre.genre_name %></td>
        </tr>
        <tr>
          <td>価格</td>
          <td>$ <%= number_with_precision(@item.price.to_s(:delimited), precision: 2) %></td>
        </tr>
        <tr>
          <td style="width: 40%;">販売ステータス</td>
          <td>
            <% if @item.is_active == "販売中" %>
              <span style="color:#49C918;"><%= @item.is_active %></sapn>
            <% else %>
              <span style="color:#C0C2BF;"><%= @item.is_active %></sapn>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
        
    <div class="actions text-center col-12 mr-5 mb-5 mt-3">
      <%= link_to '編集する', edit_admin_item_path(@item.id), class:"btn btn-success px-5 py-2" %>
    </div>
    
  </div>  
</div>