config/routes.rb
Rails.application.routes.draw do


#devise関連
devise_for :users, :controllers => {
  :registrations => 'devise/users/registrations',
  :sessions => 'devise/users/sessions',
  :passwords => 'devise/users/passwords'
}

devise_scope :user do
  get "user/:id", :to => "users/registrations#detail"
  get "signup", :to => "users/registrations#new"
  get "login", :to => "users/sessions#new"
  get "logout", :to => "users/sessions#destroy"
  get "password", :to => "users/passwords#new"
end

#Adminのdevise
devise_for :admins, :controllers => {
  :registrations => 'devise/admins/registrations',
  :sessions => 'devise/admins/sessions',
  :passwords => 'devise/admins/passwords'
}



#Top画面
root to: 'public/homes#top'
get '/about' => 'public/homes#about'

#scope module: :public doでpublicフォルダへまとめる。※URLにpublicがつくことはない
scope module: :public do

  get 'search/search'
  get 'search/genre_search'
  get 'sort' => 'items#sort'
  get 'genre_sort' => 'search#genre_sort'
  get 'search_sort' => 'search#search_sort'

  get 'items/condition_search' => 'items#condition_search'
  resources :items, only: [:index, :show] do
    resources :reviews
  end

  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :create, :destroy, :destroy_all, :update] do
    collection do
      post :shipping_confirm
    end
  end


  get 'orders/thanks' => 'orders#thanks'
  resources :orders, only: [:show, :index, :new, :create] do
    collection do
      post :confirm
      post :pay
    end
  end

  patch 'users/:id/update_password' => 'users#update_password', as: 'update_password'
  get 'users/:id/newpassword' => 'users#newpassword'
  get 'users/unsubscribe' => 'users#unsubscribe'
  patch 'users/withdraw' => 'users#withdraw'
  resources :users, only: [:update, :show, :edit]

  resources :deliveries, only: [:update, :index, :create, :destroy, :edit]

end

#お問い合わせのルーティング
post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
post 'contacts/back', to: 'contacts#back', as: 'back'
get 'done', to: 'contacts#done', as: 'done'
resources :contacts, only: [:new, :create]

#devise以外のadminを下にまとめる

namespace :admin do
  resources :items, only: [:index, :create, :new, :update, :destroy, :show, :edit]
end

namespace :admin do
  resources :genres, only: [:index, :create, :new, :update, :destroy, :show, :edit]
end

namespace :admin do
  resources :users, only: [:index, :edit, :update, :show]
end

namespace :admin do
  resources :orders, only: [:index, :show, :update]
end

namespace :admin do
  resources :order_details, only: [:update]
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :item
  belongs_to :user
  
  
 
  def subtotal_price
    (amount * item.price)
  end
  
  def international_shipping_fee
    international_shipping_fee = 0
    case country 
      when "GB","FR","DE","IT","ES","SE" 
        international_shipping_fee += 15.00
      when "IQ","IL", "EG","TR","YE","OM","ET","NG", "JM","AR","BR","GH"
        international_shipping_fee += 12.00
      when "US","CA", "MX","AU","PE"
        international_shipping_fee += 9.00
      when "PH","RU", "TW","CN","VN", "MY", "KR"
        international_shipping_fee += 7.00  
      when "JP" 
        international_shipping_fee += 4.00    
    end
  end
  
  def delivery_time
    case country
    when "GB","FR","DE","IT","ES","SE"
      p "7-9 working days"
    when "IQ","IL", "EG","TR","YE","OM","ET","NG", "JM","AR","BR","GH"
      p "6-7 working days"
    when "US","CA", "MX","AU","PE"
      p "5-6 working days"
    when "PH","RU", "TW","CN","VN", "MY", "KR"
      p "3-4 working days"
    when "JP"
      p "1-2 working days"
    end
  end
  
  
  def country_name
    c = ISO3166::Country[self.country]
    return c.translations[I18n.locale.to_s] || c.name
  end


end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  
  before_action :correct_user, only: [:update, :destroy]
  
  def index
    @cart_items = CartItem.all
    @user = User.find(current_user.id)
  end

  def create 
    @cart_item = current_user.cart_items.new(cart_item_params)
    @cart_item.save!
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    flash[:notice] = "You have removed the item"
    redirect_to cart_items_path
  end

  def destroy_all
    @user = User.find(current_user.id)
    @user.cart_items.destroy_all
    flash[:notice] = "You have emptied all items"
    redirect_to cart_items_path
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end
  
  def correct_user
		@cart_item = CartItem.find(params[:id])
		if current_user.id != @cart_item.user_id
		  flash[:alert] = "You are not autholized."
			redirect_to cart_items_path
		end
  end
  
  def cart_item_params
    params.require(:cart_item).permit(:amount, :item_id)
  end
  
  
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class="container-fluid">
	<div class="row mx-2">
		<div class="ec-cart-index-main col-md-12">
			<h2 class="ec-cart-index-title">Shopping Cart</h2>
			<!-- success-massageはlayout.html -->

			<div class="btn-box text-right">
				<%= link_to "Empty the cart", cart_items_destroy_all_path, method: :delete, class:"btn btn-danger" %>
			</div>
			<!-- カート商品一覧 -->
			<div class="cart-item-table row">
				<table class="table01 table table-sm">
    <thead class="active">
      <tr>
        <th colspan="2">Product name</th>
        <th class="text-center">Unit price</th>
        <th class="text-center">Amount</th>
        <th class="text-center">Subtotal</th>
        <th></th>
      </tr>
    </thead>
    <tbody style="background-color: #F0F3EF;">
      <% @user.cart_items.each do |cart_item| %>
      <tr>
        <th><%= attachment_image_tag cart_item.item, :image, size: "100x100", fallback: "no-image.jpeg", format: "jpeg", class: "card" %></th>
        <td data-label="Product name" class="text-center"><p><%= cart_item.item.item_name %></p></td>
        <td data-label="Unit price" class="text-center"><p>$ <%= number_with_precision(cart_item.item.price, precision: 2) %></p></td>
        <td data-label="Amount" class="text-center" style="white-space: nowrap;" >
        	<%= form_with model: cart_item, class:"form-inline",local:true do |f| %>
						<div class="mx-auto">
							<%= f.select :amount,(1..10).to_a, {}, class: "form-control" %>
							<%= f.submit "Edit", class:"btn btn-primary" %>
					  </div>
					<% end %>
        </td>
        <td data-label="Subtotal" class="text-center"><p>$ <%= number_with_precision(cart_item.subtotal_price, precision: 2) %></p></td><!-- cart_item.subtotal_priceはcart_item.rbに記載 -->
				<td class="text-right"><p><%= link_to "Remove", cart_item_path(cart_item.id), method: :delete, class:"btn btn-danger" %></p></td>
       </tr>
       <% end %>
    </tbody>
  </table>
			</div>

			<!-- 合計金額 -->
			<div class="cart-total-table row">
				<div class="col-md-8 return-shopping-btn-wrapper"><%= link_to "Continue Shopping", items_path, class:"btn btn-outline-success mb-3" %></div>
				<div class="col-md-4 ">
					<table class="table">
						<tbody class="active-grand-total active">
							<th>Grand total</th><!-- クラス名を後ほど作成。とりあえずの名前 -->
							<td class="text-right">$ <%= number_with_precision(@user.cart_item_sum, precision: 2) %></td><!-- cart_item_sumはuserモデルに定義あり -->
						</tbody>
					</table>
				</div>
			</div>
			<!-- ボタン群 -->
      <% if current_user.cart_items.present? %>
				<div class="create-order-btn-wrapper col-xs-4 col-xs-offset-4 mb-5 text-center">
					<%= link_to "Proceed to cheakout", new_order_path, class:"btn btn-primary form-control mt-4", style:"width: 60%;" %>
        </div>
      <% end %>
		</div>
	</div>
</div>