config/routes.rb
Rails.application.routes.draw do


#devise関連
devise_for :users, :controllers => {
  :registrations => 'devise/users/registrations',
  :sessions => 'devise/users/sessions',
  :passwords => 'devise/users/passwords'
}

devise_scope :user do
  get "user/:id", :to => "users/registrations#detail"
  get "signup", :to => "users/registrations#new"
  get "login", :to => "users/sessions#new"
  get "logout", :to => "users/sessions#destroy"
  get "password", :to => "users/passwords#new"
end

#Adminのdevise
devise_for :admins, :controllers => {
  :registrations => 'devise/admins/registrations',
  :sessions => 'devise/admins/sessions',
  :passwords => 'devise/admins/passwords'
}



#Top画面
root to: 'public/homes#top'
get '/about' => 'public/homes#about'

#scope module: :public doでpublicフォルダへまとめる。※URLにpublicがつくことはない
scope module: :public do

  get 'search/search'
  get 'search/genre_search'
  get 'sort' => 'items#sort'
  get 'genre_sort' => 'search#genre_sort'
  get 'search_sort' => 'search#search_sort'

  get 'items/condition_search' => 'items#condition_search'
  resources :items, only: [:index, :show] do
    resources :reviews
  end

  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :create, :destroy, :destroy_all, :update] do
    collection do
      post :shipping_confirm
    end
  end


  get 'orders/thanks' => 'orders#thanks'
  resources :orders, only: [:show, :index, :new, :create] do
    collection do
      post :confirm
      post :pay
    end
  end

  patch 'users/:id/update_password' => 'users#update_password', as: 'update_password'
  get 'users/:id/newpassword' => 'users#newpassword'
  get 'users/unsubscribe' => 'users#unsubscribe'
  patch 'users/withdraw' => 'users#withdraw'
  resources :users, only: [:update, :show, :edit]

  resources :deliveries, only: [:update, :index, :create, :destroy, :edit]

end

#お問い合わせのルーティング
post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
post 'contacts/back', to: 'contacts#back', as: 'back'
get 'done', to: 'contacts#done', as: 'done'
resources :contacts, only: [:new, :create]

#devise以外のadminを下にまとめる

namespace :admin do
  resources :items, only: [:index, :create, :new, :update, :destroy, :show, :edit]
end

namespace :admin do
  resources :genres, only: [:index, :create, :new, :update, :destroy, :show, :edit]
end

namespace :admin do
  resources :users, only: [:index, :edit, :update, :show]
end

namespace :admin do
  resources :orders, only: [:index, :show, :update]
end

namespace :admin do
  resources :order_details, only: [:update]
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  
  validates :image, presence: true
  validates :item_name, length: {minimum: 1, maximum:60}, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, numericality: true, presence: true
  
  has_many :reviews
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  attachment :image
  
  enum is_active:{販売中:true, 販売停止中:false}
  
  def self.sort(selection)
    case selection
      when 'new'
        return all.order(created_at: :DESC)
      when 'high'
        return all.order(price: :DESC)
      when 'low'
        return all.order(price: :ASC)
    end  
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    #@items = Item.all.order(created_at: :desc)
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(8)
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "製品の登録をしました。"
    redirect_to admin_items_path
    else
      render :new
    end
  end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    if @item.save
      flash[:notice] = "製品の編集を保存しました。"
      redirect_to admin_items_path
    else
      render :new
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    flash[:notice] = "製品を削除しました。"
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :item_name, :image, :introduction, :price, :is_active)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def index
    @items = Item.all.order(created_at: :desc)
    @genres = Genre.all
  end

  def show
    @item = Item.find(params[:id])
  end
  
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<div class="container-fluid">
  <div class="row">
    <h2 class="py-3 col-12 text-center" style="border-bottom: 2px dashed #EBE9DE; background-color: #101626; color:white;">Snacks</h2>
    <table class="table table-bordered genre-table mt-4 col-md-2 col-sm-3 col-xs-2 px-1">
      <thead>
        <tr>
          <th>Categories</th>
        </tr>
      </thead>
      <tbody>
      <% @genres.each do |genre| %>
        <tr>
          <td>
            <%= link_to genre.genre_name, search_search_path('search[value]': genre.id, 'search[how]': "match"), style:"color: black;" %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <div class="items col-md-10 col-sm-9 col-xs-10 mx-auto mt-4" style="padding-bottom: 50px;">

      <% @items.each do |item| %>
      <div class="card" style="width: 18rem; min-height: 340px;">
        <span><%= attachment_image_tag item, :image, size:"190x160", fallback: "no-image.jpeg",class:"card-img-top", format: "jpeg" %></span>
        <div class="card-body">
          <h5 class="card-title" style="height: 40%;"><%= item.item_name %></h5>
          <p class="card-text">$ <%= number_with_precision(item.price, precision: 2) %></p>
          <%= link_to 'Explore', item_path(item), class: 'btn btn-primary' %>
        </div>
      </div>
      <% end %>

    </div>

  </div>
</div>

app/views/items/show.html.erb
<div class="container">
  <h2 class="mt-4 mb-4">Product detail</h2>
  <div class="row"  style="padding-bottom: 70px;">
    <div class="col-lg-5 col-sm-12">
      <%= attachment_image_tag @item, :image, size: "450x450", fallback: "no-image.jpeg", format: "jpeg", class: "card" %>
    </div>
    <div class="col-lg-5 offset-lg-1 col-sm-11 col-md-10">
      <h2>Brand name</h2>
      <h3 style="margin-bottom: 30px;"><%= @item.item_name %></h3>
      <h5 style="margin-bottom: 30px;"><%= @item.introduction %></h5>
      <h2 style="margin-bottom: 30px;">$ <%= number_with_precision(@item.price, precision: 2) %></h2>

      <% if current_user %>
        <%= form_with model: @cart_items,url: cart_items_path, local:true, scope: :cart_item do |f|  %>
          <%= f.select :amount,(1..10).to_a, {}, class: "form-control product-show-form-control" %>
          <%= f.hidden_field :item_id, :value => @item.id %>
          <%= f.submit 'Add to cart', class: "btn btn-success btn-new-register btn-lg mt-4"%>
        <% end %>
      <% end %>  
    </div>
  </div>
</div>