config/routes.rb
Rails.application.routes.draw do


#devise関連
devise_for :users, :controllers => {
  :registrations => 'devise/users/registrations',
  :sessions => 'devise/users/sessions',
  :passwords => 'devise/users/passwords'
}

devise_scope :user do
  get "user/:id", :to => "users/registrations#detail"
  get "signup", :to => "users/registrations#new"
  get "login", :to => "users/sessions#new"
  get "logout", :to => "users/sessions#destroy"
  get "password", :to => "users/passwords#new"
end

#Adminのdevise
devise_for :admins, :controllers => {
  :registrations => 'devise/admins/registrations',
  :sessions => 'devise/admins/sessions',
  :passwords => 'devise/admins/passwords'
}



#Top画面
root to: 'public/homes#top'
get '/about' => 'public/homes#about'

#scope module: :public doでpublicフォルダへまとめる。※URLにpublicがつくことはない
scope module: :public do

  get 'search/search'
  get 'search/genre_search'
  get 'sort' => 'items#sort'
  get 'genre_sort' => 'search#genre_sort'
  get 'search_sort' => 'search#search_sort'

  get 'items/condition_search' => 'items#condition_search'
  resources :items, only: [:index, :show] do
    resources :reviews
  end

  delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :create, :destroy, :destroy_all, :update] do
    collection do
      post :shipping_confirm
    end
  end


  get 'orders/thanks' => 'orders#thanks'
  resources :orders, only: [:show, :index, :new, :create] do
    collection do
      post :confirm
      post :pay
    end
  end

  patch 'users/:id/update_password' => 'users#update_password', as: 'update_password'
  get 'users/:id/newpassword' => 'users#newpassword'
  get 'users/unsubscribe' => 'users#unsubscribe'
  patch 'users/withdraw' => 'users#withdraw'
  resources :users, only: [:update, :show, :edit]

  resources :deliveries, only: [:update, :index, :create, :destroy, :edit]

end

#お問い合わせのルーティング
post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
post 'contacts/back', to: 'contacts#back', as: 'back'
get 'done', to: 'contacts#done', as: 'done'
resources :contacts, only: [:new, :create]

#devise以外のadminを下にまとめる

namespace :admin do
  resources :items, only: [:index, :create, :new, :update, :destroy, :show, :edit]
end

namespace :admin do
  resources :genres, only: [:index, :create, :new, :update, :destroy, :show, :edit]
end

namespace :admin do
  resources :users, only: [:index, :edit, :update, :show]
end

namespace :admin do
  resources :orders, only: [:index, :show, :update]
end

namespace :admin do
  resources :order_details, only: [:update]
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnackBen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- Ensures optimal rendering on mobile devices. -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&family=Abril+Fatface&family=Chango&family=Ranchers&display=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
  </head>
  <body class="body-background-color">
    <div class="header-message-section">
      <p class="pt-2 mx-4 text-center header-message">Authentic Japanese snacks packed with care and delivered to your door</p>
    </div>
    <div style="background-color:#EBE9DE; height: 41px;">
      <div class="d-flex justify-content-end mx-4">
        <div class="d-flex justify-content-start">
          <% unless admin_signed_in? %>
            <li class="pt-2 search-section-list">
              <%# ↓自作検索機能。検索の仕組みを学習する為、ここではransackを使わず自作検索機能を作った。  ボタンを左側に置ききたい為、button_tagが先 %>
              <div class="search-section">
                <%= form_with url: search_search_path, method: :get, class:"d-flex flex-row form-inline", local:true do |f| %>
                  <%= button_tag :type => "submit", :class =>"search-button" do %>
                    <i class="fa fa-search"></i>
                  <% end %>
                  <%= f.text_field 'search[value]', class:"mr-3 search-form", autocomplete:"off" %>
                  <%#　今回のアプリでは一致検索不要。後学のためコメントアウトで残す⇨。<%= f.select 'search[how]', options_for_select({ "Partical" => "partical", "Forward" => "forward", "Backword" => "backward", "Match" => "match" }), {}, {style: 'height: 35px;'} %>
                <% end %>
              </div>
            </li>
            <span class="pt-2" style="color: #D6D6D5;">|</span>
            <p class="pt-1">
              <%= link_to new_contact_path, class:"nav-link contact-link" do %>
                <i class="fas fa-envelope mr-2"></i>CONTACT US
              <% end %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
    <header class="sticky-top">
      <nav class="navbar navbar-expand-lg navbar-light py-3" style="background-color: black;">
        <div class="container-fluid">
          <button class="navbar-toggler" style="background-color: #EBE9DE;" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <h1 class="pt-1 brand-center header-title">SNACKBEN</h1>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

              <% if user_signed_in? %>
              <li class="nav-item">
                <a class="nav-link" href="/" style="color: #EBE9DE;">HOME <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle", style="color: #EBE9DE;", href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  SHOP
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%  @genres.each do |genre| %>
                    <%= link_to genre.genre_name, search_genre_search_path('search[content]': genre.id), class:"nav-link", style:"color: #EBE9DE;"  %>
                  <% end %>
                  <%= link_to 'ALL', items_path, class:"nav-link", style:"color: #EBE9DE;" %>
                </div>
              </li>
              <li class="nav-item">
                <%= link_to 'ABOUT', '/about', class:"nav-link", style:"color: #EBE9DE;" %>
              </li>
              <li class="nav-item">
                <%= link_to 'SIGN OUT', destroy_user_session_path, method: :delete, data:{ confirm: 'Are you sure you want to do this?',cancel: 'Cancel',commit: 'Yes'}, title:'Sign Out', class:"nav-link", style:"color: #EBE9DE;" %>
              </li>

              <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to '商品⼀覧', admin_items_path, class: " nav-link", style:"color: #EBE9DE;" %>
              </li>
              <li class="nav-item">
                <%= link_to '会員⼀覧', admin_users_path, class: " nav-link", style:"color: #EBE9DE;" %>
              </li>
              <li class="nav-item">
                <%= link_to '注⽂履歴⼀覧', admin_orders_path, class: " nav-link", style:"color: #EBE9DE;" %>
              </li>
              <li class="nav-item">
                <%= link_to 'ジャンル⼀覧', admin_genres_path , class: " nav-link", style:"color: #EBE9DE;" %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, data:{ confirm: '本当にログアウトしますか?',cancel: 'いいえ',commit: 'はい'}, title: 'ログアウト', class:"nav-link", style:"color: #EBE9DE;" %>
              </li>

              <% else %>
              <li class="nav-item">
                <a class="nav-link" href="/" style="color: #EBE9DE;">HOME <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle", style="color: #EBE9DE;", href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  SHOP
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%  @genres.each do |genre| %>
                    <%= link_to genre.genre_name, search_genre_search_path('search[content]': genre.id), class:"nav-link", style:"color: #EBE9DE;"  %>
                  <% end %>
                  <%= link_to 'ALL', items_path, class:"nav-link", style:"color: #EBE9DE;" %>
                </div>
              </li>
              <li class="nav-item">
                <%= link_to 'ABOUT', '/about', class:"nav-link", style:"color: #EBE9DE;" %>
              </li>

              <% end %>
            </ul>
            <%# ここからheaderブランド名の右側 %>
            <% if user_signed_in? %>
              <li class="ml-3"><%= link_to 'Your Account Page', user_path(current_user), style:"color: #EBE9DE;" %></sapn>
            <% end %>
            <% unless user_signed_in? || admin_signed_in?  %>
              <%#<li class="nav-item">
                <%= link_to 'Sign up', new_user_registration_path, class:"nav-link", style:"color: #EBE9DE;" %>
              <%#</li>  下でサインイン・サインアップ一つのボタンにまとめる %>
              <li class="nav-item" style="margin-left: 3px;"><%# レスポンシブの時、他のリストとインデント合わせるマージン %>
                <%= link_to 'LOG IN / REGISTER', new_user_session_path, class:"nav-link", style:"color: #EBE9DE;" %>
              </li>
            <% end %>

          </div>

          <!-- 携帯画面にしたときにハンバーガーアイコンに隠れないようにdivで囲む　-->
          <div class="d-flex">

          <% if user_signed_in?  %>
            <%= link_to cart_items_path, class:"nav-link", style:"color: #EBE9DE;" do %>
              <li class="d-flex flex-row cart-circle-relative mt-1 remove">
                <i class="fas fa-shopping-cart my-auto mr-1"></i><div class="cart-circle"><span><%= current_user.cart_total_count %></span></div><%# cart_toal_count user.rbに記述 %>
              </li>
            <% end %>
          <% end %>
          </div>

        </div>
      </nav>
    </header>

    <main>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="flash" style="color: red;">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
    </main>
    <div class="contact-form">
      <div class="container">
        <div class="row">
          <h1 class="col-lg-4">SNACKBEN</h1>
          <div class="col-lg-4 mt-3">
            <h4 class="cantact-heading">HELP & INFORMATION</h4>
            <%= link_to 'About Us', '/about', class:"nav-link", style:"color: #EBE9DE;" %>
            <%= link_to 'Inquiry', new_contact_path, class:"nav-link", style:"color: #EBE9DE;" %>
          </div>
          <div class="col-lg-4 mt-3">
            <h4>MY ACCOUNT</h4>
            <% if user_signed_in? %>
              <p class="ml-3"><%= link_to 'Your Account Page', user_path(current_user), style:"color: #EBE9DE;" %></p>
            <% else %>
              <p><%= link_to 'Log In / Register', new_user_session_path, class:"nav-link", style:"color: #EBE9DE;" %></p>
            <% end %>
          </div>
          <p class="ml-4">(c) SNACKBEN 2021</p>
        </div>
      </div>
      <img src="<%= asset_path "ben.kanji.png" %>" class="footer-pic"></img>
    </div>
  </body>
</html>